# Generated by Django 5.0.1 on 2024-01-31 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='color',
            field=models.CharField(default='default_color_value', max_length=50),
        ),
    ]
