# Generated by Django 5.0.1 on 2024-02-02 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='telecaller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.telecaller'),
        ),
    ]
