# Generated by Django 5.0.1 on 2024-03-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_administrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='telecaller',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
    ]
